### ISSUE TITLE
home - header - purple corner

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/cityofmadera#1]
how would you create that shape with css to match the template?

**Comment by geekwise-alonzo-yrigollen** [comment]
border radius?

**Comment by Sramos9191** [comment]
not entirely, look up “css shapes”

**Comment by geekwise-alonzo-yrigollen** [comment]
i pushed is it rendering? if so this issue will show completed? @Sramos9191 6/8/2016
