### ISSUE TITLE
home - header - search icon #featured

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/cityofmadera#2]
font awesome should allow you to insert the search icon

**Comment by geekwise-alonzo-yrigollen** [comment]
got it....whoohoooo! i love the feeling when i figured it out. referred back to my git....dusty buns site. I may need to go buy me a sandwich from them just cause they made me happy...thats a joke btw...hope it at least made ya smile. Peace be with you @Sramos9191 always
